# Generated by Django 4.2.17 on 2024-12-09 19:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название игры', max_length=70)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Цена', max_digits=10)),
                ('size', models.DecimalField(decimal_places=3, help_text='Размер файлов в GB', max_digits=3)),
                ('description', models.TextField(help_text='Описание игры')),
                ('age_limited', models.BooleanField(default=False, help_text='Ограничение по возрасту 18+')),
                ('buyer', models.ManyToManyField(related_name='games', to='task1.buyer')),
            ],
        ),
    ]
